name: workflows

on:
    push:
        branches:
            - dev-br

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            - name: Run a one-line script
              run: echo "Hello, GitHub Actions!"