name: Workflows
on:
    push:
        branches:
          - dev-branch
jobs:
  SAST:
    runs-on: ubuntu-latest
    steps:
        - name: Set up JDK 17
          uses: actions/setup-java@v2
          with:
            java-version: '17'
            distribution: 'adopt'

        - name: Checkout code
          uses: actions/checkout@v2
        - name: build
          ##working-directory: ./Taller-Final
          run: |
            chmod 777 gradlew
            ./gradlew build
        
        - name: Validando existencia del proyecto en Sonarqube
          id: validacionProjectSonar
          run: |
            set +e
            curl -f -X POST -u '${{secrets.TOKEN_SONAR_TALLERFINAL}}:' 'https://sonarcloud.io/api/projects/create' -d 'name=Taller-Final' -d 'project=Taller-Final' -d 'organization=curso-devsecops2025' -d 'visibility=public'
                if [ $? -ne 0 ]; then
                    echo "El proyecto ya existe en SonarQube"
                    echo "::set-output name=Projecto_Existe::1"
                else
                    echo "Proyecto ${github.event.repository.name} creado exitosamente en SonarCloud"
                    echo "Proyecto creado exitosamente"
                    curl -f -X POST -u '${{secrets.TOKEN_SONAR_TALLERFINAL}}:' 'https://sonarcloud.io/api/project_branches/rename' -d 'name=main' -d 'project=Taller-Final' -d 'visibility=public'
                fi
            set -e
